In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
## Linear regression

In [4]:
#p=10, n=1000
X=np.random.uniform(-10,10,size=(1000,10))

wtrue=np.ones(10)
print('Our true weights')
print(wtrue)

#noise
noise=np.random.normal(scale=10,size=1000)

#our data
Y=np.einsum('ij,j->i',X,wtrue)+noise

Our true weights
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
## Linear regression

In [5]:
#(X^T X)^{-1}
XtX_inv=np.linalg.inv(np.einsum('ij,jk->ik',np.transpose(X),X))

wLR=np.einsum('ij,jk,k->i',XtX_inv,np.transpose(X),Y)
wLR

array([1.06486102, 0.97986004, 1.02239283, 1.00500987, 0.96763664,
       0.92202621, 0.9961868 , 1.06001138, 1.04145662, 1.0737295 ])

In [34]:
## Ridge regression

In [6]:
Lambda=10

XtXLambda_inv=np.linalg.inv(np.einsum('ij,jk->ik',np.transpose(X),X)+Lambda*np.diag(np.ones(10)))

wRidge=np.einsum('ij,jk,k->i',XtXLambda_inv,np.transpose(X),Y)
wRidge

array([1.06453518, 0.97958347, 1.02206952, 1.00471765, 0.96730786,
       0.92170824, 0.99592169, 1.0597    , 1.04117237, 1.07340055])

In [41]:
## Comparing linear and ridge regression

In [7]:
yRidge=np.einsum('ij,j->i',X,wRidge)
yLR=np.einsum('ij,j->i',X,wLR)

In [8]:
# just to get a glimpse (repeat this multiple times for robust results):
np.mean(np.abs(yLR)-np.abs(yRidge))

0.004456752423717003

In [60]:
U, D, Vt = np.linalg.svd(X, full_matrices=True)
print(np.shape(U))
print(np.shape(D))
print(np.shape(Vt))

(1000, 1000)
(10,)
(10, 10)


In [64]:
# X^T X = V D^2 V^T
np.einsum('ij,jk->ik',np.transpose(X),X)-np.einsum('ij,j,jk->ik',np.transpose(Vt),D**2,Vt)
# V^T V
np.einsum('ij,jk->ik',Vt,np.transpose(Vt))

[[-1.09139364e-10  3.75166564e-11  1.19371180e-11  3.06954462e-12
  -1.88720151e-11  8.86757334e-12 -4.09272616e-12 -2.09183781e-11
   1.59161573e-11  1.70530257e-11]
 [ 3.69482223e-11  7.27595761e-12 -1.53477231e-11  1.40971679e-11
  -1.73372428e-12  4.18367563e-11  1.95541361e-11  7.50333129e-12
   1.43245416e-11 -1.50066626e-11]
 [ 1.28466127e-11 -1.35287337e-11 -1.01863407e-10 -1.05870868e-11
   7.16227078e-12 -4.00177669e-11 -1.36424205e-11 -3.52429197e-12
   7.73070497e-12  1.70530257e-11]
 [ 2.16004992e-12  1.54614099e-11 -1.04733999e-11  4.72937245e-11
  -3.92219590e-11 -3.06954462e-12  1.79625204e-11  4.12114787e-12
   4.54747351e-13  1.18234311e-11]
 [-1.79625204e-11 -1.27897692e-12  6.93489710e-12 -4.14956958e-11
  -6.54836185e-11  2.98996383e-11 -5.22959454e-12  5.45696821e-12
   1.02318154e-12  5.00222086e-11]
 [ 8.86757334e-12  4.18367563e-11 -4.00177669e-11 -3.06954462e-12
   2.98996383e-11 -2.91038305e-11 -3.41060513e-12 -6.13908924e-12
   1.42108547e-12 -2.52384780e-11

array([[ 1.00000000e+00,  0.00000000e+00,  1.94289029e-16,
         2.91433544e-16, -1.11022302e-16, -2.77555756e-17,
         1.52655666e-16, -1.11022302e-16,  4.16333634e-17,
         1.38777878e-16],
       [ 0.00000000e+00,  1.00000000e+00, -4.57966998e-16,
        -4.16333634e-16,  5.55111512e-17,  2.98372438e-16,
         0.00000000e+00, -4.16333634e-16,  3.05311332e-16,
        -4.02455846e-16],
       [ 1.94289029e-16, -4.57966998e-16,  1.00000000e+00,
        -1.21430643e-16, -1.11022302e-16,  1.38777878e-17,
        -8.32667268e-17,  2.77555756e-17,  6.93889390e-18,
         1.38777878e-17],
       [ 2.91433544e-16, -4.16333634e-16, -1.21430643e-16,
         1.00000000e+00,  3.05311332e-16, -4.09394740e-16,
        -6.24500451e-17, -1.80411242e-16,  2.87964097e-16,
        -3.19189120e-16],
       [-1.11022302e-16,  5.55111512e-17, -1.11022302e-16,
         3.05311332e-16,  1.00000000e+00,  1.04083409e-16,
        -1.24900090e-16, -1.66533454e-16, -1.38777878e-17,
        -2.